/*
 * Copyright (c) 2012, Metron, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Metron, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL METRON, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.23 at 06:04:48 PM EST
//


package com.metsci.glimpse.charts.vector.display.xmlgen;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationFontSpec.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AnnotationFontSpec">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Monospace_8_BY_13"/>
 *     &lt;enumeration value="Monospace_9_BY_15"/>
 *     &lt;enumeration value="Times_Roman_10"/>
 *     &lt;enumeration value="Times_Roman_24"/>
 *     &lt;enumeration value="Helvetical_10"/>
 *     &lt;enumeration value="Helvetical_12"/>
 *     &lt;enumeration value="Helvetical_18"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "AnnotationFontSpec")
@XmlEnum
public enum AnnotationFontSpec {

    @XmlEnumValue("Monospace_8_BY_13")
    MONOSPACE_8_BY_13("Monospace_8_BY_13"),
    @XmlEnumValue("Monospace_9_BY_15")
    MONOSPACE_9_BY_15("Monospace_9_BY_15"),
    @XmlEnumValue("Times_Roman_10")
    TIMES_ROMAN_10("Times_Roman_10"),
    @XmlEnumValue("Times_Roman_24")
    TIMES_ROMAN_24("Times_Roman_24"),
    @XmlEnumValue("Helvetical_10")
    HELVETICAL_10("Helvetical_10"),
    @XmlEnumValue("Helvetical_12")
    HELVETICAL_12("Helvetical_12"),
    @XmlEnumValue("Helvetical_18")
    HELVETICAL_18("Helvetical_18");
    private final String value;

    AnnotationFontSpec(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AnnotationFontSpec fromValue(String v) {
        for (AnnotationFontSpec c: AnnotationFontSpec.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
