/*
 * Copyright (c) 2012, Metron, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Metron, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL METRON, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.23 at 06:04:48 PM EST
//


package com.metsci.glimpse.charts.vector.display.xmlgen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationPainterSpec complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AnnotationPainterSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="centerX" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="centerY" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="color" type="{http://geo.metsci.com}ColorSpec" minOccurs="0"/>
 *         &lt;element name="font" type="{http://geo.metsci.com}AnnotationFontSpec" minOccurs="0"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="offset_x" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="offset_y" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotationPainterSpec", propOrder = {
    "centerX",
    "centerY",
    "color",
    "font",
    "height",
    "offsetX",
    "offsetY",
    "text",
    "x",
    "y"
})
@XmlSeeAlso({
    EncAnnotationPainterSpec.class,
    DncAnnotationPainterSpec.class
})
public abstract class AnnotationPainterSpec {

    @XmlElement(defaultValue = "true")
    protected Boolean centerX;
    @XmlElement(defaultValue = "true")
    protected Boolean centerY;
    protected ColorSpec color;
    protected AnnotationFontSpec font;
    protected Integer height;
    @XmlElement(name = "offset_x")
    protected Integer offsetX;
    @XmlElement(name = "offset_y")
    protected Integer offsetY;
    protected String text;
    protected Float x;
    protected Float y;

    /**
     * Gets the value of the centerX property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isCenterX() {
        return centerX;
    }

    /**
     * Sets the value of the centerX property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCenterX(Boolean value) {
        this.centerX = value;
    }

    /**
     * Gets the value of the centerY property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isCenterY() {
        return centerY;
    }

    /**
     * Sets the value of the centerY property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCenterY(Boolean value) {
        this.centerY = value;
    }

    /**
     * Gets the value of the color property.
     *
     * @return
     *     possible object is
     *     {@link ColorSpec }
     *
     */
    public ColorSpec getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     *
     * @param value
     *     allowed object is
     *     {@link ColorSpec }
     *
     */
    public void setColor(ColorSpec value) {
        this.color = value;
    }

    /**
     * Gets the value of the font property.
     *
     * @return
     *     possible object is
     *     {@link AnnotationFontSpec }
     *
     */
    public AnnotationFontSpec getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     *
     * @param value
     *     allowed object is
     *     {@link AnnotationFontSpec }
     *
     */
    public void setFont(AnnotationFontSpec value) {
        this.font = value;
    }

    /**
     * Gets the value of the height property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the offsetX property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getOffsetX() {
        return offsetX;
    }

    /**
     * Sets the value of the offsetX property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setOffsetX(Integer value) {
        this.offsetX = value;
    }

    /**
     * Gets the value of the offsetY property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getOffsetY() {
        return offsetY;
    }

    /**
     * Sets the value of the offsetY property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setOffsetY(Integer value) {
        this.offsetY = value;
    }

    /**
     * Gets the value of the text property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the x property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setX(Float value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setY(Float value) {
        this.y = value;
    }

}
