/*
 * Copyright (c) 2012, Metron, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Metron, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL METRON, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.23 at 06:04:48 PM EST
//


package com.metsci.glimpse.charts.vector.display.xmlgen;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncAttributeTypeSpec.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EncAttributeTypeSpec">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AgencyResponsibleForProduction"/>
 *     &lt;enumeration value="BeaconShape"/>
 *     &lt;enumeration value="BuildingShape"/>
 *     &lt;enumeration value="BuoyShape"/>
 *     &lt;enumeration value="BuriedDepth"/>
 *     &lt;enumeration value="CallSign"/>
 *     &lt;enumeration value="CategoryOfAirportAirfield"/>
 *     &lt;enumeration value="CategoryOfAnchorage"/>
 *     &lt;enumeration value="CategoryOfBridge"/>
 *     &lt;enumeration value="CategoryOfBuiltUpArea"/>
 *     &lt;enumeration value="CategoryOfCable"/>
 *     &lt;enumeration value="CategoryOfCanal"/>
 *     &lt;enumeration value="CategoryOfCardinalMark"/>
 *     &lt;enumeration value="CategoryOfCheckpoint"/>
 *     &lt;enumeration value="CategoryOfCoastline"/>
 *     &lt;enumeration value="CategoryOfConveyor"/>
 *     &lt;enumeration value="CategoryOfControlPoint"/>
 *     &lt;enumeration value="CategoryOfCrane"/>
 *     &lt;enumeration value="CategoryOfCoverage"/>
 *     &lt;enumeration value="CategoryOfDistanceMark"/>
 *     &lt;enumeration value="CategoryOfDam"/>
 *     &lt;enumeration value="CategoryOfDumpingGround"/>
 *     &lt;enumeration value="CategoryOfDock"/>
 *     &lt;enumeration value="CategoryOfFerry"/>
 *     &lt;enumeration value="CategoryOfFenceWall"/>
 *     &lt;enumeration value="CategoryOfFogSignal"/>
 *     &lt;enumeration value="CategoryOfFishingFacility"/>
 *     &lt;enumeration value="CategoryOfGate"/>
 *     &lt;enumeration value="CategoryOfFortifiedStructure"/>
 *     &lt;enumeration value="CategoryOfHulk"/>
 *     &lt;enumeration value="CategoryOfHarbourFacility"/>
 *     &lt;enumeration value="CategoryOfLandRegion"/>
 *     &lt;enumeration value="CategoryOfLandmark"/>
 *     &lt;enumeration value="CategoryOfIce"/>
 *     &lt;enumeration value="CategoryOfInstallationBuoy"/>
 *     &lt;enumeration value="CategoryOfMarineFarmCulture"/>
 *     &lt;enumeration value="CategoryOfMilitaryPracticeArea"/>
 *     &lt;enumeration value="CategoryOfLateralMark"/>
 *     &lt;enumeration value="CategoryOfLight"/>
 *     &lt;enumeration value="CategoryOfObstruction"/>
 *     &lt;enumeration value="CategoryOfOffshorePlatform"/>
 *     &lt;enumeration value="CategoryOfMooringWarpingFacility"/>
 *     &lt;enumeration value="CategoryOfNavigationLine"/>
 *     &lt;enumeration value="CategoryOfPilotBoardingPlace"/>
 *     &lt;enumeration value="CategoryOfPipelinePipe"/>
 *     &lt;enumeration value="CategoryOfOilBarrier"/>
 *     &lt;enumeration value="CategoryOfPile"/>
 *     &lt;enumeration value="CategoryOfRadarStation"/>
 *     &lt;enumeration value="CategoryOfQualityOfData"/>
 *     &lt;enumeration value="CategoryOfPylon"/>
 *     &lt;enumeration value="CategoryOfProductionArea"/>
 *     &lt;enumeration value="CategoryOfRescueStation"/>
 *     &lt;enumeration value="CategoryOfRecommendedTrack"/>
 *     &lt;enumeration value="CategoryOfRadioStation"/>
 *     &lt;enumeration value="CategoryOfRadarTransponderBeacon"/>
 *     &lt;enumeration value="CategoryOfSeaArea"/>
 *     &lt;enumeration value="CategoryOfRunway"/>
 *     &lt;enumeration value="CategoryOfRoad"/>
 *     &lt;enumeration value="CategoryOfRestrictedArea"/>
 *     &lt;enumeration value="CategoryOfSiloTank"/>
 *     &lt;enumeration value="CategoryOfSignalStationWarning"/>
 *     &lt;enumeration value="CategoryOfSignalStationTraffic"/>
 *     &lt;enumeration value="CategoryOfShorelineConstruction"/>
 *     &lt;enumeration value="CategoryOfVegetation"/>
 *     &lt;enumeration value="CategoryOfWaterTurbulence"/>
 *     &lt;enumeration value="CategoryOfWeedKelp"/>
 *     &lt;enumeration value="CategoryOfWreck"/>
 *     &lt;enumeration value="CategoryOfSlope"/>
 *     &lt;enumeration value="CategoryOfSmallCraftFacility"/>
 *     &lt;enumeration value="CategoryOfSpecialPurposeMark"/>
 *     &lt;enumeration value="CategoryOfTrafficSeparationScheme"/>
 *     &lt;enumeration value="ColourPattern"/>
 *     &lt;enumeration value="CommunicationChannel"/>
 *     &lt;enumeration value="CompassSize"/>
 *     &lt;enumeration value="CompilationDate"/>
 *     &lt;enumeration value="CategoryOfZoneOfConfidenceData"/>
 *     &lt;enumeration value="CharacterSpacing"/>
 *     &lt;enumeration value="CharacterSpecification"/>
 *     &lt;enumeration value="Colour"/>
 *     &lt;enumeration value="DateEnd"/>
 *     &lt;enumeration value="CurrentVelocity"/>
 *     &lt;enumeration value="DepthRangeValue1"/>
 *     &lt;enumeration value="DateStart"/>
 *     &lt;enumeration value="Condition"/>
 *     &lt;enumeration value="CompilationScale"/>
 *     &lt;enumeration value="ConspicuousVisual"/>
 *     &lt;enumeration value="ConspicuousRadar"/>
 *     &lt;enumeration value="ExpositionOfSounding"/>
 *     &lt;enumeration value="ExhibitionConditionOfLight"/>
 *     &lt;enumeration value="Height"/>
 *     &lt;enumeration value="Function"/>
 *     &lt;enumeration value="DepthUnits"/>
 *     &lt;enumeration value="DepthRangeValue2"/>
 *     &lt;enumeration value="EstimatedRangeOfTransmission"/>
 *     &lt;enumeration value="Elevation"/>
 *     &lt;enumeration value="Information"/>
 *     &lt;enumeration value="Jurisdiction"/>
 *     &lt;enumeration value="HorizontalWidth"/>
 *     &lt;enumeration value="IceFactor"/>
 *     &lt;enumeration value="HorizontalClearance"/>
 *     &lt;enumeration value="HorizontalLength"/>
 *     &lt;enumeration value="HeightLengthUnits"/>
 *     &lt;enumeration value="HorizontalAccuracy"/>
 *     &lt;enumeration value="MultiplicityOfLights"/>
 *     &lt;enumeration value="Nationality"/>
 *     &lt;enumeration value="LightVisibility"/>
 *     &lt;enumeration value="MarksNavigationalSystemOf"/>
 *     &lt;enumeration value="LiftingCapacity"/>
 *     &lt;enumeration value="LightCharacteristic"/>
 *     &lt;enumeration value="JustificationHorizontal"/>
 *     &lt;enumeration value="JustificationVertical"/>
 *     &lt;enumeration value="PeriodicDateStart"/>
 *     &lt;enumeration value="PeriodicDateEnd"/>
 *     &lt;enumeration value="Orientation"/>
 *     &lt;enumeration value="ObjectName"/>
 *     &lt;enumeration value="NoticeToMarinersDate"/>
 *     &lt;enumeration value="NatureOfSurfaceQualifyingTerms"/>
 *     &lt;enumeration value="NatureOfSurface"/>
 *     &lt;enumeration value="NatureOfConstruction"/>
 *     &lt;enumeration value="Radius"/>
 *     &lt;enumeration value="RadarWaveLength"/>
 *     &lt;enumeration value="QualityOfSoundingMeasurement"/>
 *     &lt;enumeration value="PublicationReference"/>
 *     &lt;enumeration value="Product"/>
 *     &lt;enumeration value="ProducingCountry"/>
 *     &lt;enumeration value="PilotDistrict"/>
 *     &lt;enumeration value="PictorialRepresentation"/>
 *     &lt;enumeration value="SectorLimitTwo"/>
 *     &lt;enumeration value="SectorLimitOne"/>
 *     &lt;enumeration value="SignalFrequency"/>
 *     &lt;enumeration value="ShiftParameters"/>
 *     &lt;enumeration value="SignalGroup"/>
 *     &lt;enumeration value="SignalGeneration"/>
 *     &lt;enumeration value="SignalSequence"/>
 *     &lt;enumeration value="SignalPeriod"/>
 *     &lt;enumeration value="RecordingIndication"/>
 *     &lt;enumeration value="RecordingDate"/>
 *     &lt;enumeration value="Restriction"/>
 *     &lt;enumeration value="ReferenceYearForMagneticVariation"/>
 *     &lt;enumeration value="ScaleMinimum"/>
 *     &lt;enumeration value="ScaleMaximum"/>
 *     &lt;enumeration value="ScaleValueTwo"/>
 *     &lt;enumeration value="ScaleValueOne"/>
 *     &lt;enumeration value="SurveyDateStart"/>
 *     &lt;enumeration value="SurveyType"/>
 *     &lt;enumeration value="SymbolScalingFactor"/>
 *     &lt;enumeration value="SymbolizationCode"/>
 *     &lt;enumeration value="TechniqueOfSoundingMeasurement"/>
 *     &lt;enumeration value="TextString"/>
 *     &lt;enumeration value="TextualDescription"/>
 *     &lt;enumeration value="TidalStreamPanelValues"/>
 *     &lt;enumeration value="SoundingAccuracy"/>
 *     &lt;enumeration value="SoundingDistanceMaximum"/>
 *     &lt;enumeration value="SoundingDistanceMinimum"/>
 *     &lt;enumeration value="SourceDate"/>
 *     &lt;enumeration value="SourceIndication"/>
 *     &lt;enumeration value="Status"/>
 *     &lt;enumeration value="SurveyAuthority"/>
 *     &lt;enumeration value="SurveyDateEnd"/>
 *     &lt;enumeration value="TopmarkDaymarkShape"/>
 *     &lt;enumeration value="Tint"/>
 *     &lt;enumeration value="TimeStart"/>
 *     &lt;enumeration value="TimeEnd"/>
 *     &lt;enumeration value="ValueOfLocalMagneticAnomaly"/>
 *     &lt;enumeration value="ValueOfDepthContour"/>
 *     &lt;enumeration value="ValueOfAnnualChangeInMagneticVariation"/>
 *     &lt;enumeration value="TrafficFlow"/>
 *     &lt;enumeration value="TideMethodOfTidalPrediction"/>
 *     &lt;enumeration value="TideHighAndLowWaterValues"/>
 *     &lt;enumeration value="TideAccuracyOfWaterLevel"/>
 *     &lt;enumeration value="TidalStreamCurrentTimeSeriesValues"/>
 *     &lt;enumeration value="TideValueOfHarmonicConstituents"/>
 *     &lt;enumeration value="TideTimeSeriesValues"/>
 *     &lt;enumeration value="TideCurrentTimeIntervalOfValues"/>
 *     &lt;enumeration value="TideTimeAndHeightDifferences"/>
 *     &lt;enumeration value="VerticalLength"/>
 *     &lt;enumeration value="WaterLevelEffect"/>
 *     &lt;enumeration value="VerticalClearanceSafe"/>
 *     &lt;enumeration value="VerticalDatum"/>
 *     &lt;enumeration value="CategoryOfTidalStream"/>
 *     &lt;enumeration value="PositionalAccuracyUnits"/>
 *     &lt;enumeration value="ValueOfNominalRange"/>
 *     &lt;enumeration value="ValueOfSounding"/>
 *     &lt;enumeration value="ValueOfMagneticVariation"/>
 *     &lt;enumeration value="ValueOfMaximumRange"/>
 *     &lt;enumeration value="VerticalClearanceClosed"/>
 *     &lt;enumeration value="VerticalClearanceOpen"/>
 *     &lt;enumeration value="VerticalAccuracy"/>
 *     &lt;enumeration value="VerticalClearance"/>
 *     &lt;enumeration value="TextualDescriptionInNationalLanguage"/>
 *     &lt;enumeration value="InformationInNationalLanguage"/>
 *     &lt;enumeration value="ObjectNameInNationalLanguage"/>
 *     &lt;enumeration value="PilotDistrictInNationalLanguage"/>
 *     &lt;enumeration value="TextStringInNationalLanguage"/>
 *     &lt;enumeration value="QualityOfPosition"/>
 *     &lt;enumeration value="HorizontalDatum"/>
 *     &lt;enumeration value="PositionalAccuracy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "EncAttributeTypeSpec")
@XmlEnum
public enum EncAttributeTypeSpec {

    @XmlEnumValue("AgencyResponsibleForProduction")
    AGENCY_RESPONSIBLE_FOR_PRODUCTION("AgencyResponsibleForProduction"),
    @XmlEnumValue("BeaconShape")
    BEACON_SHAPE("BeaconShape"),
    @XmlEnumValue("BuildingShape")
    BUILDING_SHAPE("BuildingShape"),
    @XmlEnumValue("BuoyShape")
    BUOY_SHAPE("BuoyShape"),
    @XmlEnumValue("BuriedDepth")
    BURIED_DEPTH("BuriedDepth"),
    @XmlEnumValue("CallSign")
    CALL_SIGN("CallSign"),
    @XmlEnumValue("CategoryOfAirportAirfield")
    CATEGORY_OF_AIRPORT_AIRFIELD("CategoryOfAirportAirfield"),
    @XmlEnumValue("CategoryOfAnchorage")
    CATEGORY_OF_ANCHORAGE("CategoryOfAnchorage"),
    @XmlEnumValue("CategoryOfBridge")
    CATEGORY_OF_BRIDGE("CategoryOfBridge"),
    @XmlEnumValue("CategoryOfBuiltUpArea")
    CATEGORY_OF_BUILT_UP_AREA("CategoryOfBuiltUpArea"),
    @XmlEnumValue("CategoryOfCable")
    CATEGORY_OF_CABLE("CategoryOfCable"),
    @XmlEnumValue("CategoryOfCanal")
    CATEGORY_OF_CANAL("CategoryOfCanal"),
    @XmlEnumValue("CategoryOfCardinalMark")
    CATEGORY_OF_CARDINAL_MARK("CategoryOfCardinalMark"),
    @XmlEnumValue("CategoryOfCheckpoint")
    CATEGORY_OF_CHECKPOINT("CategoryOfCheckpoint"),
    @XmlEnumValue("CategoryOfCoastline")
    CATEGORY_OF_COASTLINE("CategoryOfCoastline"),
    @XmlEnumValue("CategoryOfConveyor")
    CATEGORY_OF_CONVEYOR("CategoryOfConveyor"),
    @XmlEnumValue("CategoryOfControlPoint")
    CATEGORY_OF_CONTROL_POINT("CategoryOfControlPoint"),
    @XmlEnumValue("CategoryOfCrane")
    CATEGORY_OF_CRANE("CategoryOfCrane"),
    @XmlEnumValue("CategoryOfCoverage")
    CATEGORY_OF_COVERAGE("CategoryOfCoverage"),
    @XmlEnumValue("CategoryOfDistanceMark")
    CATEGORY_OF_DISTANCE_MARK("CategoryOfDistanceMark"),
    @XmlEnumValue("CategoryOfDam")
    CATEGORY_OF_DAM("CategoryOfDam"),
    @XmlEnumValue("CategoryOfDumpingGround")
    CATEGORY_OF_DUMPING_GROUND("CategoryOfDumpingGround"),
    @XmlEnumValue("CategoryOfDock")
    CATEGORY_OF_DOCK("CategoryOfDock"),
    @XmlEnumValue("CategoryOfFerry")
    CATEGORY_OF_FERRY("CategoryOfFerry"),
    @XmlEnumValue("CategoryOfFenceWall")
    CATEGORY_OF_FENCE_WALL("CategoryOfFenceWall"),
    @XmlEnumValue("CategoryOfFogSignal")
    CATEGORY_OF_FOG_SIGNAL("CategoryOfFogSignal"),
    @XmlEnumValue("CategoryOfFishingFacility")
    CATEGORY_OF_FISHING_FACILITY("CategoryOfFishingFacility"),
    @XmlEnumValue("CategoryOfGate")
    CATEGORY_OF_GATE("CategoryOfGate"),
    @XmlEnumValue("CategoryOfFortifiedStructure")
    CATEGORY_OF_FORTIFIED_STRUCTURE("CategoryOfFortifiedStructure"),
    @XmlEnumValue("CategoryOfHulk")
    CATEGORY_OF_HULK("CategoryOfHulk"),
    @XmlEnumValue("CategoryOfHarbourFacility")
    CATEGORY_OF_HARBOUR_FACILITY("CategoryOfHarbourFacility"),
    @XmlEnumValue("CategoryOfLandRegion")
    CATEGORY_OF_LAND_REGION("CategoryOfLandRegion"),
    @XmlEnumValue("CategoryOfLandmark")
    CATEGORY_OF_LANDMARK("CategoryOfLandmark"),
    @XmlEnumValue("CategoryOfIce")
    CATEGORY_OF_ICE("CategoryOfIce"),
    @XmlEnumValue("CategoryOfInstallationBuoy")
    CATEGORY_OF_INSTALLATION_BUOY("CategoryOfInstallationBuoy"),
    @XmlEnumValue("CategoryOfMarineFarmCulture")
    CATEGORY_OF_MARINE_FARM_CULTURE("CategoryOfMarineFarmCulture"),
    @XmlEnumValue("CategoryOfMilitaryPracticeArea")
    CATEGORY_OF_MILITARY_PRACTICE_AREA("CategoryOfMilitaryPracticeArea"),
    @XmlEnumValue("CategoryOfLateralMark")
    CATEGORY_OF_LATERAL_MARK("CategoryOfLateralMark"),
    @XmlEnumValue("CategoryOfLight")
    CATEGORY_OF_LIGHT("CategoryOfLight"),
    @XmlEnumValue("CategoryOfObstruction")
    CATEGORY_OF_OBSTRUCTION("CategoryOfObstruction"),
    @XmlEnumValue("CategoryOfOffshorePlatform")
    CATEGORY_OF_OFFSHORE_PLATFORM("CategoryOfOffshorePlatform"),
    @XmlEnumValue("CategoryOfMooringWarpingFacility")
    CATEGORY_OF_MOORING_WARPING_FACILITY("CategoryOfMooringWarpingFacility"),
    @XmlEnumValue("CategoryOfNavigationLine")
    CATEGORY_OF_NAVIGATION_LINE("CategoryOfNavigationLine"),
    @XmlEnumValue("CategoryOfPilotBoardingPlace")
    CATEGORY_OF_PILOT_BOARDING_PLACE("CategoryOfPilotBoardingPlace"),
    @XmlEnumValue("CategoryOfPipelinePipe")
    CATEGORY_OF_PIPELINE_PIPE("CategoryOfPipelinePipe"),
    @XmlEnumValue("CategoryOfOilBarrier")
    CATEGORY_OF_OIL_BARRIER("CategoryOfOilBarrier"),
    @XmlEnumValue("CategoryOfPile")
    CATEGORY_OF_PILE("CategoryOfPile"),
    @XmlEnumValue("CategoryOfRadarStation")
    CATEGORY_OF_RADAR_STATION("CategoryOfRadarStation"),
    @XmlEnumValue("CategoryOfQualityOfData")
    CATEGORY_OF_QUALITY_OF_DATA("CategoryOfQualityOfData"),
    @XmlEnumValue("CategoryOfPylon")
    CATEGORY_OF_PYLON("CategoryOfPylon"),
    @XmlEnumValue("CategoryOfProductionArea")
    CATEGORY_OF_PRODUCTION_AREA("CategoryOfProductionArea"),
    @XmlEnumValue("CategoryOfRescueStation")
    CATEGORY_OF_RESCUE_STATION("CategoryOfRescueStation"),
    @XmlEnumValue("CategoryOfRecommendedTrack")
    CATEGORY_OF_RECOMMENDED_TRACK("CategoryOfRecommendedTrack"),
    @XmlEnumValue("CategoryOfRadioStation")
    CATEGORY_OF_RADIO_STATION("CategoryOfRadioStation"),
    @XmlEnumValue("CategoryOfRadarTransponderBeacon")
    CATEGORY_OF_RADAR_TRANSPONDER_BEACON("CategoryOfRadarTransponderBeacon"),
    @XmlEnumValue("CategoryOfSeaArea")
    CATEGORY_OF_SEA_AREA("CategoryOfSeaArea"),
    @XmlEnumValue("CategoryOfRunway")
    CATEGORY_OF_RUNWAY("CategoryOfRunway"),
    @XmlEnumValue("CategoryOfRoad")
    CATEGORY_OF_ROAD("CategoryOfRoad"),
    @XmlEnumValue("CategoryOfRestrictedArea")
    CATEGORY_OF_RESTRICTED_AREA("CategoryOfRestrictedArea"),
    @XmlEnumValue("CategoryOfSiloTank")
    CATEGORY_OF_SILO_TANK("CategoryOfSiloTank"),
    @XmlEnumValue("CategoryOfSignalStationWarning")
    CATEGORY_OF_SIGNAL_STATION_WARNING("CategoryOfSignalStationWarning"),
    @XmlEnumValue("CategoryOfSignalStationTraffic")
    CATEGORY_OF_SIGNAL_STATION_TRAFFIC("CategoryOfSignalStationTraffic"),
    @XmlEnumValue("CategoryOfShorelineConstruction")
    CATEGORY_OF_SHORELINE_CONSTRUCTION("CategoryOfShorelineConstruction"),
    @XmlEnumValue("CategoryOfVegetation")
    CATEGORY_OF_VEGETATION("CategoryOfVegetation"),
    @XmlEnumValue("CategoryOfWaterTurbulence")
    CATEGORY_OF_WATER_TURBULENCE("CategoryOfWaterTurbulence"),
    @XmlEnumValue("CategoryOfWeedKelp")
    CATEGORY_OF_WEED_KELP("CategoryOfWeedKelp"),
    @XmlEnumValue("CategoryOfWreck")
    CATEGORY_OF_WRECK("CategoryOfWreck"),
    @XmlEnumValue("CategoryOfSlope")
    CATEGORY_OF_SLOPE("CategoryOfSlope"),
    @XmlEnumValue("CategoryOfSmallCraftFacility")
    CATEGORY_OF_SMALL_CRAFT_FACILITY("CategoryOfSmallCraftFacility"),
    @XmlEnumValue("CategoryOfSpecialPurposeMark")
    CATEGORY_OF_SPECIAL_PURPOSE_MARK("CategoryOfSpecialPurposeMark"),
    @XmlEnumValue("CategoryOfTrafficSeparationScheme")
    CATEGORY_OF_TRAFFIC_SEPARATION_SCHEME("CategoryOfTrafficSeparationScheme"),
    @XmlEnumValue("ColourPattern")
    COLOUR_PATTERN("ColourPattern"),
    @XmlEnumValue("CommunicationChannel")
    COMMUNICATION_CHANNEL("CommunicationChannel"),
    @XmlEnumValue("CompassSize")
    COMPASS_SIZE("CompassSize"),
    @XmlEnumValue("CompilationDate")
    COMPILATION_DATE("CompilationDate"),
    @XmlEnumValue("CategoryOfZoneOfConfidenceData")
    CATEGORY_OF_ZONE_OF_CONFIDENCE_DATA("CategoryOfZoneOfConfidenceData"),
    @XmlEnumValue("CharacterSpacing")
    CHARACTER_SPACING("CharacterSpacing"),
    @XmlEnumValue("CharacterSpecification")
    CHARACTER_SPECIFICATION("CharacterSpecification"),
    @XmlEnumValue("Colour")
    COLOUR("Colour"),
    @XmlEnumValue("DateEnd")
    DATE_END("DateEnd"),
    @XmlEnumValue("CurrentVelocity")
    CURRENT_VELOCITY("CurrentVelocity"),
    @XmlEnumValue("DepthRangeValue1")
    DEPTH_RANGE_VALUE_1("DepthRangeValue1"),
    @XmlEnumValue("DateStart")
    DATE_START("DateStart"),
    @XmlEnumValue("Condition")
    CONDITION("Condition"),
    @XmlEnumValue("CompilationScale")
    COMPILATION_SCALE("CompilationScale"),
    @XmlEnumValue("ConspicuousVisual")
    CONSPICUOUS_VISUAL("ConspicuousVisual"),
    @XmlEnumValue("ConspicuousRadar")
    CONSPICUOUS_RADAR("ConspicuousRadar"),
    @XmlEnumValue("ExpositionOfSounding")
    EXPOSITION_OF_SOUNDING("ExpositionOfSounding"),
    @XmlEnumValue("ExhibitionConditionOfLight")
    EXHIBITION_CONDITION_OF_LIGHT("ExhibitionConditionOfLight"),
    @XmlEnumValue("Height")
    HEIGHT("Height"),
    @XmlEnumValue("Function")
    FUNCTION("Function"),
    @XmlEnumValue("DepthUnits")
    DEPTH_UNITS("DepthUnits"),
    @XmlEnumValue("DepthRangeValue2")
    DEPTH_RANGE_VALUE_2("DepthRangeValue2"),
    @XmlEnumValue("EstimatedRangeOfTransmission")
    ESTIMATED_RANGE_OF_TRANSMISSION("EstimatedRangeOfTransmission"),
    @XmlEnumValue("Elevation")
    ELEVATION("Elevation"),
    @XmlEnumValue("Information")
    INFORMATION("Information"),
    @XmlEnumValue("Jurisdiction")
    JURISDICTION("Jurisdiction"),
    @XmlEnumValue("HorizontalWidth")
    HORIZONTAL_WIDTH("HorizontalWidth"),
    @XmlEnumValue("IceFactor")
    ICE_FACTOR("IceFactor"),
    @XmlEnumValue("HorizontalClearance")
    HORIZONTAL_CLEARANCE("HorizontalClearance"),
    @XmlEnumValue("HorizontalLength")
    HORIZONTAL_LENGTH("HorizontalLength"),
    @XmlEnumValue("HeightLengthUnits")
    HEIGHT_LENGTH_UNITS("HeightLengthUnits"),
    @XmlEnumValue("HorizontalAccuracy")
    HORIZONTAL_ACCURACY("HorizontalAccuracy"),
    @XmlEnumValue("MultiplicityOfLights")
    MULTIPLICITY_OF_LIGHTS("MultiplicityOfLights"),
    @XmlEnumValue("Nationality")
    NATIONALITY("Nationality"),
    @XmlEnumValue("LightVisibility")
    LIGHT_VISIBILITY("LightVisibility"),
    @XmlEnumValue("MarksNavigationalSystemOf")
    MARKS_NAVIGATIONAL_SYSTEM_OF("MarksNavigationalSystemOf"),
    @XmlEnumValue("LiftingCapacity")
    LIFTING_CAPACITY("LiftingCapacity"),
    @XmlEnumValue("LightCharacteristic")
    LIGHT_CHARACTERISTIC("LightCharacteristic"),
    @XmlEnumValue("JustificationHorizontal")
    JUSTIFICATION_HORIZONTAL("JustificationHorizontal"),
    @XmlEnumValue("JustificationVertical")
    JUSTIFICATION_VERTICAL("JustificationVertical"),
    @XmlEnumValue("PeriodicDateStart")
    PERIODIC_DATE_START("PeriodicDateStart"),
    @XmlEnumValue("PeriodicDateEnd")
    PERIODIC_DATE_END("PeriodicDateEnd"),
    @XmlEnumValue("Orientation")
    ORIENTATION("Orientation"),
    @XmlEnumValue("ObjectName")
    OBJECT_NAME("ObjectName"),
    @XmlEnumValue("NoticeToMarinersDate")
    NOTICE_TO_MARINERS_DATE("NoticeToMarinersDate"),
    @XmlEnumValue("NatureOfSurfaceQualifyingTerms")
    NATURE_OF_SURFACE_QUALIFYING_TERMS("NatureOfSurfaceQualifyingTerms"),
    @XmlEnumValue("NatureOfSurface")
    NATURE_OF_SURFACE("NatureOfSurface"),
    @XmlEnumValue("NatureOfConstruction")
    NATURE_OF_CONSTRUCTION("NatureOfConstruction"),
    @XmlEnumValue("Radius")
    RADIUS("Radius"),
    @XmlEnumValue("RadarWaveLength")
    RADAR_WAVE_LENGTH("RadarWaveLength"),
    @XmlEnumValue("QualityOfSoundingMeasurement")
    QUALITY_OF_SOUNDING_MEASUREMENT("QualityOfSoundingMeasurement"),
    @XmlEnumValue("PublicationReference")
    PUBLICATION_REFERENCE("PublicationReference"),
    @XmlEnumValue("Product")
    PRODUCT("Product"),
    @XmlEnumValue("ProducingCountry")
    PRODUCING_COUNTRY("ProducingCountry"),
    @XmlEnumValue("PilotDistrict")
    PILOT_DISTRICT("PilotDistrict"),
    @XmlEnumValue("PictorialRepresentation")
    PICTORIAL_REPRESENTATION("PictorialRepresentation"),
    @XmlEnumValue("SectorLimitTwo")
    SECTOR_LIMIT_TWO("SectorLimitTwo"),
    @XmlEnumValue("SectorLimitOne")
    SECTOR_LIMIT_ONE("SectorLimitOne"),
    @XmlEnumValue("SignalFrequency")
    SIGNAL_FREQUENCY("SignalFrequency"),
    @XmlEnumValue("ShiftParameters")
    SHIFT_PARAMETERS("ShiftParameters"),
    @XmlEnumValue("SignalGroup")
    SIGNAL_GROUP("SignalGroup"),
    @XmlEnumValue("SignalGeneration")
    SIGNAL_GENERATION("SignalGeneration"),
    @XmlEnumValue("SignalSequence")
    SIGNAL_SEQUENCE("SignalSequence"),
    @XmlEnumValue("SignalPeriod")
    SIGNAL_PERIOD("SignalPeriod"),
    @XmlEnumValue("RecordingIndication")
    RECORDING_INDICATION("RecordingIndication"),
    @XmlEnumValue("RecordingDate")
    RECORDING_DATE("RecordingDate"),
    @XmlEnumValue("Restriction")
    RESTRICTION("Restriction"),
    @XmlEnumValue("ReferenceYearForMagneticVariation")
    REFERENCE_YEAR_FOR_MAGNETIC_VARIATION("ReferenceYearForMagneticVariation"),
    @XmlEnumValue("ScaleMinimum")
    SCALE_MINIMUM("ScaleMinimum"),
    @XmlEnumValue("ScaleMaximum")
    SCALE_MAXIMUM("ScaleMaximum"),
    @XmlEnumValue("ScaleValueTwo")
    SCALE_VALUE_TWO("ScaleValueTwo"),
    @XmlEnumValue("ScaleValueOne")
    SCALE_VALUE_ONE("ScaleValueOne"),
    @XmlEnumValue("SurveyDateStart")
    SURVEY_DATE_START("SurveyDateStart"),
    @XmlEnumValue("SurveyType")
    SURVEY_TYPE("SurveyType"),
    @XmlEnumValue("SymbolScalingFactor")
    SYMBOL_SCALING_FACTOR("SymbolScalingFactor"),
    @XmlEnumValue("SymbolizationCode")
    SYMBOLIZATION_CODE("SymbolizationCode"),
    @XmlEnumValue("TechniqueOfSoundingMeasurement")
    TECHNIQUE_OF_SOUNDING_MEASUREMENT("TechniqueOfSoundingMeasurement"),
    @XmlEnumValue("TextString")
    TEXT_STRING("TextString"),
    @XmlEnumValue("TextualDescription")
    TEXTUAL_DESCRIPTION("TextualDescription"),
    @XmlEnumValue("TidalStreamPanelValues")
    TIDAL_STREAM_PANEL_VALUES("TidalStreamPanelValues"),
    @XmlEnumValue("SoundingAccuracy")
    SOUNDING_ACCURACY("SoundingAccuracy"),
    @XmlEnumValue("SoundingDistanceMaximum")
    SOUNDING_DISTANCE_MAXIMUM("SoundingDistanceMaximum"),
    @XmlEnumValue("SoundingDistanceMinimum")
    SOUNDING_DISTANCE_MINIMUM("SoundingDistanceMinimum"),
    @XmlEnumValue("SourceDate")
    SOURCE_DATE("SourceDate"),
    @XmlEnumValue("SourceIndication")
    SOURCE_INDICATION("SourceIndication"),
    @XmlEnumValue("Status")
    STATUS("Status"),
    @XmlEnumValue("SurveyAuthority")
    SURVEY_AUTHORITY("SurveyAuthority"),
    @XmlEnumValue("SurveyDateEnd")
    SURVEY_DATE_END("SurveyDateEnd"),
    @XmlEnumValue("TopmarkDaymarkShape")
    TOPMARK_DAYMARK_SHAPE("TopmarkDaymarkShape"),
    @XmlEnumValue("Tint")
    TINT("Tint"),
    @XmlEnumValue("TimeStart")
    TIME_START("TimeStart"),
    @XmlEnumValue("TimeEnd")
    TIME_END("TimeEnd"),
    @XmlEnumValue("ValueOfLocalMagneticAnomaly")
    VALUE_OF_LOCAL_MAGNETIC_ANOMALY("ValueOfLocalMagneticAnomaly"),
    @XmlEnumValue("ValueOfDepthContour")
    VALUE_OF_DEPTH_CONTOUR("ValueOfDepthContour"),
    @XmlEnumValue("ValueOfAnnualChangeInMagneticVariation")
    VALUE_OF_ANNUAL_CHANGE_IN_MAGNETIC_VARIATION("ValueOfAnnualChangeInMagneticVariation"),
    @XmlEnumValue("TrafficFlow")
    TRAFFIC_FLOW("TrafficFlow"),
    @XmlEnumValue("TideMethodOfTidalPrediction")
    TIDE_METHOD_OF_TIDAL_PREDICTION("TideMethodOfTidalPrediction"),
    @XmlEnumValue("TideHighAndLowWaterValues")
    TIDE_HIGH_AND_LOW_WATER_VALUES("TideHighAndLowWaterValues"),
    @XmlEnumValue("TideAccuracyOfWaterLevel")
    TIDE_ACCURACY_OF_WATER_LEVEL("TideAccuracyOfWaterLevel"),
    @XmlEnumValue("TidalStreamCurrentTimeSeriesValues")
    TIDAL_STREAM_CURRENT_TIME_SERIES_VALUES("TidalStreamCurrentTimeSeriesValues"),
    @XmlEnumValue("TideValueOfHarmonicConstituents")
    TIDE_VALUE_OF_HARMONIC_CONSTITUENTS("TideValueOfHarmonicConstituents"),
    @XmlEnumValue("TideTimeSeriesValues")
    TIDE_TIME_SERIES_VALUES("TideTimeSeriesValues"),
    @XmlEnumValue("TideCurrentTimeIntervalOfValues")
    TIDE_CURRENT_TIME_INTERVAL_OF_VALUES("TideCurrentTimeIntervalOfValues"),
    @XmlEnumValue("TideTimeAndHeightDifferences")
    TIDE_TIME_AND_HEIGHT_DIFFERENCES("TideTimeAndHeightDifferences"),
    @XmlEnumValue("VerticalLength")
    VERTICAL_LENGTH("VerticalLength"),
    @XmlEnumValue("WaterLevelEffect")
    WATER_LEVEL_EFFECT("WaterLevelEffect"),
    @XmlEnumValue("VerticalClearanceSafe")
    VERTICAL_CLEARANCE_SAFE("VerticalClearanceSafe"),
    @XmlEnumValue("VerticalDatum")
    VERTICAL_DATUM("VerticalDatum"),
    @XmlEnumValue("CategoryOfTidalStream")
    CATEGORY_OF_TIDAL_STREAM("CategoryOfTidalStream"),
    @XmlEnumValue("PositionalAccuracyUnits")
    POSITIONAL_ACCURACY_UNITS("PositionalAccuracyUnits"),
    @XmlEnumValue("ValueOfNominalRange")
    VALUE_OF_NOMINAL_RANGE("ValueOfNominalRange"),
    @XmlEnumValue("ValueOfSounding")
    VALUE_OF_SOUNDING("ValueOfSounding"),
    @XmlEnumValue("ValueOfMagneticVariation")
    VALUE_OF_MAGNETIC_VARIATION("ValueOfMagneticVariation"),
    @XmlEnumValue("ValueOfMaximumRange")
    VALUE_OF_MAXIMUM_RANGE("ValueOfMaximumRange"),
    @XmlEnumValue("VerticalClearanceClosed")
    VERTICAL_CLEARANCE_CLOSED("VerticalClearanceClosed"),
    @XmlEnumValue("VerticalClearanceOpen")
    VERTICAL_CLEARANCE_OPEN("VerticalClearanceOpen"),
    @XmlEnumValue("VerticalAccuracy")
    VERTICAL_ACCURACY("VerticalAccuracy"),
    @XmlEnumValue("VerticalClearance")
    VERTICAL_CLEARANCE("VerticalClearance"),
    @XmlEnumValue("TextualDescriptionInNationalLanguage")
    TEXTUAL_DESCRIPTION_IN_NATIONAL_LANGUAGE("TextualDescriptionInNationalLanguage"),
    @XmlEnumValue("InformationInNationalLanguage")
    INFORMATION_IN_NATIONAL_LANGUAGE("InformationInNationalLanguage"),
    @XmlEnumValue("ObjectNameInNationalLanguage")
    OBJECT_NAME_IN_NATIONAL_LANGUAGE("ObjectNameInNationalLanguage"),
    @XmlEnumValue("PilotDistrictInNationalLanguage")
    PILOT_DISTRICT_IN_NATIONAL_LANGUAGE("PilotDistrictInNationalLanguage"),
    @XmlEnumValue("TextStringInNationalLanguage")
    TEXT_STRING_IN_NATIONAL_LANGUAGE("TextStringInNationalLanguage"),
    @XmlEnumValue("QualityOfPosition")
    QUALITY_OF_POSITION("QualityOfPosition"),
    @XmlEnumValue("HorizontalDatum")
    HORIZONTAL_DATUM("HorizontalDatum"),
    @XmlEnumValue("PositionalAccuracy")
    POSITIONAL_ACCURACY("PositionalAccuracy");
    private final String value;

    EncAttributeTypeSpec(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EncAttributeTypeSpec fromValue(String v) {
        for (EncAttributeTypeSpec c: EncAttributeTypeSpec.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
