/*
 * Copyright (c) 2012, Metron, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Metron, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL METRON, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.23 at 06:04:48 PM EST
//


package com.metsci.glimpse.charts.vector.display.xmlgen;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.metsci.glimpse.support.enc.display.xmlgen package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.metsci.glimpse.support.enc.display.xmlgen
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrackPainterSpec }
     *
     */
    public TrackPainterSpec createTrackPainterSpec() {
        return new TrackPainterSpec();
    }

    /**
     * Create an instance of {@link ShapeSpec }
     *
     */
    public ShapeSpec createShapeSpec() {
        return new ShapeSpec();
    }

    /**
     * Create an instance of {@link PolygonPainterSpec }
     *
     */
    public PolygonPainterSpec createPolygonPainterSpec() {
        return new PolygonPainterSpec();
    }

    /**
     * Create an instance of {@link ColorSpec }
     *
     */
    public ColorSpec createColorSpec() {
        return new ColorSpec();
    }

    /**
     * Create an instance of {@link Geoskinspec }
     *
     */
    public Geoskinspec createGeoskinspec() {
        return new Geoskinspec();
    }

    /**
     * Create an instance of {@link PainterSpec }
     *
     */
    public PainterSpec createPainterSpec() {
        return new PainterSpec();
    }

    /**
     * Create an instance of {@link DncAnnotationPainterSpec }
     *
     */
    public DncAnnotationPainterSpec createDncAnnotationPainterSpec() {
        return new DncAnnotationPainterSpec();
    }

    /**
     * Create an instance of {@link EncAnnotationPainterSpec }
     *
     */
    public EncAnnotationPainterSpec createEncAnnotationPainterSpec() {
        return new EncAnnotationPainterSpec();
    }

    /**
     * Create an instance of {@link FeatureSpec }
     *
     */
    public FeatureSpec createFeatureSpec() {
        return new FeatureSpec();
    }

}
