//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.23 at 06:04:48 PM EST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://geo.metsci.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.metsci.glimpse.charts.vector.display.xmlgen;
