/*
 * Copyright (c) 2012, Metron, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Metron, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL METRON, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.23 at 06:04:48 PM EST
//


package com.metsci.glimpse.charts.vector.display.xmlgen;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PainterSpec complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PainterSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="polygonpainterspec" type="{http://geo.metsci.com}PolygonPainterSpec"/>
 *         &lt;element name="trackpainterspec" type="{http://geo.metsci.com}TrackPainterSpec"/>
 *         &lt;element name="annotationpainterspec" type="{http://geo.metsci.com}AnnotationPainterSpec"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PainterSpec", propOrder = {
    "polygonpainterspecOrTrackpainterspecOrAnnotationpainterspec"
})
public class PainterSpec {

    @XmlElements({
        @XmlElement(name = "trackpainterspec", type = TrackPainterSpec.class),
        @XmlElement(name = "annotationpainterspec", type = AnnotationPainterSpec.class),
        @XmlElement(name = "polygonpainterspec", type = PolygonPainterSpec.class)
    })
    protected List<Object> polygonpainterspecOrTrackpainterspecOrAnnotationpainterspec;

    /**
     * Gets the value of the polygonpainterspecOrTrackpainterspecOrAnnotationpainterspec property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the polygonpainterspecOrTrackpainterspecOrAnnotationpainterspec property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolygonpainterspecOrTrackpainterspecOrAnnotationpainterspec().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrackPainterSpec }
     * {@link AnnotationPainterSpec }
     * {@link PolygonPainterSpec }
     *
     *
     */
    public List<Object> getPolygonpainterspecOrTrackpainterspecOrAnnotationpainterspec() {
        if (polygonpainterspecOrTrackpainterspecOrAnnotationpainterspec == null) {
            polygonpainterspecOrTrackpainterspecOrAnnotationpainterspec = new ArrayList<Object>();
        }
        return this.polygonpainterspecOrTrackpainterspecOrAnnotationpainterspec;
    }

}
