/*
 * Copyright (c) 2012, Metron, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Metron, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL METRON, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.23 at 06:04:48 PM EST
//


package com.metsci.glimpse.charts.vector.display.xmlgen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolygonPainterSpec complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PolygonPainterSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="showLines" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lineColor" type="{http://geo.metsci.com}ColorSpec" minOccurs="0"/>
 *         &lt;element name="lineWidth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="lineStippleFactor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="lineStipplePattern" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="lineDotted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="polyStipplePattern" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="polyDotted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="fill" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="fillColor" type="{http://geo.metsci.com}ColorSpec" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolygonPainterSpec", propOrder = {

})
public class PolygonPainterSpec {

    protected Boolean showLines;
    protected ColorSpec lineColor;
    protected Integer lineWidth;
    protected Integer lineStippleFactor;
    protected Short lineStipplePattern;
    protected Boolean lineDotted;
    protected byte[] polyStipplePattern;
    protected Boolean polyDotted;
    protected Boolean fill;
    protected ColorSpec fillColor;

    /**
     * Gets the value of the showLines property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShowLines() {
        return showLines;
    }

    /**
     * Sets the value of the showLines property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowLines(Boolean value) {
        this.showLines = value;
    }

    /**
     * Gets the value of the lineColor property.
     *
     * @return
     *     possible object is
     *     {@link ColorSpec }
     *
     */
    public ColorSpec getLineColor() {
        return lineColor;
    }

    /**
     * Sets the value of the lineColor property.
     *
     * @param value
     *     allowed object is
     *     {@link ColorSpec }
     *
     */
    public void setLineColor(ColorSpec value) {
        this.lineColor = value;
    }

    /**
     * Gets the value of the lineWidth property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setLineWidth(Integer value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the lineStippleFactor property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getLineStippleFactor() {
        return lineStippleFactor;
    }

    /**
     * Sets the value of the lineStippleFactor property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setLineStippleFactor(Integer value) {
        this.lineStippleFactor = value;
    }

    /**
     * Gets the value of the lineStipplePattern property.
     *
     * @return
     *     possible object is
     *     {@link Short }
     *
     */
    public Short getLineStipplePattern() {
        return lineStipplePattern;
    }

    /**
     * Sets the value of the lineStipplePattern property.
     *
     * @param value
     *     allowed object is
     *     {@link Short }
     *
     */
    public void setLineStipplePattern(Short value) {
        this.lineStipplePattern = value;
    }

    /**
     * Gets the value of the lineDotted property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isLineDotted() {
        return lineDotted;
    }

    /**
     * Sets the value of the lineDotted property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setLineDotted(Boolean value) {
        this.lineDotted = value;
    }

    /**
     * Gets the value of the polyStipplePattern property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPolyStipplePattern() {
        return polyStipplePattern;
    }

    /**
     * Sets the value of the polyStipplePattern property.
     *
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPolyStipplePattern(byte[] value) {
        this.polyStipplePattern = ((byte[]) value);
    }

    /**
     * Gets the value of the polyDotted property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isPolyDotted() {
        return polyDotted;
    }

    /**
     * Sets the value of the polyDotted property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPolyDotted(Boolean value) {
        this.polyDotted = value;
    }

    /**
     * Gets the value of the fill property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setFill(Boolean value) {
        this.fill = value;
    }

    /**
     * Gets the value of the fillColor property.
     *
     * @return
     *     possible object is
     *     {@link ColorSpec }
     *
     */
    public ColorSpec getFillColor() {
        return fillColor;
    }

    /**
     * Sets the value of the fillColor property.
     *
     * @param value
     *     allowed object is
     *     {@link ColorSpec }
     *
     */
    public void setFillColor(ColorSpec value) {
        this.fillColor = value;
    }

}
