/*
 * Copyright (c) 2012, Metron, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Metron, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL METRON, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.23 at 06:04:48 PM EST
//


package com.metsci.glimpse.charts.vector.display.xmlgen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrackPainterSpec complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TrackPainterSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="headPointColor" type="{http://geo.metsci.com}ColorSpec" minOccurs="0"/>
 *         &lt;element name="headPointSize" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="showHeadPoint" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="pointColor" type="{http://geo.metsci.com}ColorSpec" minOccurs="0"/>
 *         &lt;element name="pointSize" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="showPoints" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lineColor" type="{http://geo.metsci.com}ColorSpec" minOccurs="0"/>
 *         &lt;element name="lineWidth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="showLines" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dotted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="stippleFactor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stipplePattern" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="labelColor" type="{http://geo.metsci.com}ColorSpec" minOccurs="0"/>
 *         &lt;element name="labelLineColor" type="{http://geo.metsci.com}ColorSpec" minOccurs="0"/>
 *         &lt;element name="showLabelLine" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="showLabel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackPainterSpec", propOrder = {

})
public class TrackPainterSpec {

    protected ColorSpec headPointColor;
    protected Float headPointSize;
    protected Boolean showHeadPoint;
    protected ColorSpec pointColor;
    protected Float pointSize;
    protected Boolean showPoints;
    protected ColorSpec lineColor;
    protected Float lineWidth;
    protected Boolean showLines;
    protected Boolean dotted;
    protected Integer stippleFactor;
    protected Short stipplePattern;
    protected ColorSpec labelColor;
    protected ColorSpec labelLineColor;
    protected Boolean showLabelLine;
    protected String label;
    protected Boolean showLabel;

    /**
     * Gets the value of the headPointColor property.
     *
     * @return
     *     possible object is
     *     {@link ColorSpec }
     *
     */
    public ColorSpec getHeadPointColor() {
        return headPointColor;
    }

    /**
     * Sets the value of the headPointColor property.
     *
     * @param value
     *     allowed object is
     *     {@link ColorSpec }
     *
     */
    public void setHeadPointColor(ColorSpec value) {
        this.headPointColor = value;
    }

    /**
     * Gets the value of the headPointSize property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getHeadPointSize() {
        return headPointSize;
    }

    /**
     * Sets the value of the headPointSize property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setHeadPointSize(Float value) {
        this.headPointSize = value;
    }

    /**
     * Gets the value of the showHeadPoint property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShowHeadPoint() {
        return showHeadPoint;
    }

    /**
     * Sets the value of the showHeadPoint property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowHeadPoint(Boolean value) {
        this.showHeadPoint = value;
    }

    /**
     * Gets the value of the pointColor property.
     *
     * @return
     *     possible object is
     *     {@link ColorSpec }
     *
     */
    public ColorSpec getPointColor() {
        return pointColor;
    }

    /**
     * Sets the value of the pointColor property.
     *
     * @param value
     *     allowed object is
     *     {@link ColorSpec }
     *
     */
    public void setPointColor(ColorSpec value) {
        this.pointColor = value;
    }

    /**
     * Gets the value of the pointSize property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getPointSize() {
        return pointSize;
    }

    /**
     * Sets the value of the pointSize property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setPointSize(Float value) {
        this.pointSize = value;
    }

    /**
     * Gets the value of the showPoints property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShowPoints() {
        return showPoints;
    }

    /**
     * Sets the value of the showPoints property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowPoints(Boolean value) {
        this.showPoints = value;
    }

    /**
     * Gets the value of the lineColor property.
     *
     * @return
     *     possible object is
     *     {@link ColorSpec }
     *
     */
    public ColorSpec getLineColor() {
        return lineColor;
    }

    /**
     * Sets the value of the lineColor property.
     *
     * @param value
     *     allowed object is
     *     {@link ColorSpec }
     *
     */
    public void setLineColor(ColorSpec value) {
        this.lineColor = value;
    }

    /**
     * Gets the value of the lineWidth property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setLineWidth(Float value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the showLines property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShowLines() {
        return showLines;
    }

    /**
     * Sets the value of the showLines property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowLines(Boolean value) {
        this.showLines = value;
    }

    /**
     * Gets the value of the dotted property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isDotted() {
        return dotted;
    }

    /**
     * Sets the value of the dotted property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setDotted(Boolean value) {
        this.dotted = value;
    }

    /**
     * Gets the value of the stippleFactor property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getStippleFactor() {
        return stippleFactor;
    }

    /**
     * Sets the value of the stippleFactor property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setStippleFactor(Integer value) {
        this.stippleFactor = value;
    }

    /**
     * Gets the value of the stipplePattern property.
     *
     * @return
     *     possible object is
     *     {@link Short }
     *
     */
    public Short getStipplePattern() {
        return stipplePattern;
    }

    /**
     * Sets the value of the stipplePattern property.
     *
     * @param value
     *     allowed object is
     *     {@link Short }
     *
     */
    public void setStipplePattern(Short value) {
        this.stipplePattern = value;
    }

    /**
     * Gets the value of the labelColor property.
     *
     * @return
     *     possible object is
     *     {@link ColorSpec }
     *
     */
    public ColorSpec getLabelColor() {
        return labelColor;
    }

    /**
     * Sets the value of the labelColor property.
     *
     * @param value
     *     allowed object is
     *     {@link ColorSpec }
     *
     */
    public void setLabelColor(ColorSpec value) {
        this.labelColor = value;
    }

    /**
     * Gets the value of the labelLineColor property.
     *
     * @return
     *     possible object is
     *     {@link ColorSpec }
     *
     */
    public ColorSpec getLabelLineColor() {
        return labelLineColor;
    }

    /**
     * Sets the value of the labelLineColor property.
     *
     * @param value
     *     allowed object is
     *     {@link ColorSpec }
     *
     */
    public void setLabelLineColor(ColorSpec value) {
        this.labelLineColor = value;
    }

    /**
     * Gets the value of the showLabelLine property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShowLabelLine() {
        return showLabelLine;
    }

    /**
     * Sets the value of the showLabelLine property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowLabelLine(Boolean value) {
        this.showLabelLine = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the showLabel property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShowLabel() {
        return showLabel;
    }

    /**
     * Sets the value of the showLabel property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowLabel(Boolean value) {
        this.showLabel = value;
    }

}
