/**
 * Core Glimpse data structures for plots, axes, layouts and painters.
 */
module com.metsci.glimpse.core
{
    exports com.metsci.glimpse.support.texture.mutator;
    exports com.metsci.glimpse.context;
    exports com.metsci.glimpse.painter.base;
    exports com.metsci.glimpse.axis.listener;
    exports com.metsci.glimpse.event.key;
    exports com.metsci.glimpse.support.font;
    exports com.metsci.glimpse.event.mouse;
    exports com.metsci.glimpse.painter.group;
    exports com.metsci.glimpse.support.atlas;
    exports com.metsci.glimpse.painter.texture;
    exports com.metsci.glimpse.painter.shape;
    exports com.metsci.glimpse.support.shader.colormap;
    exports com.metsci.glimpse.painter.track;
    exports com.metsci.glimpse.painter.plot;
    exports com.metsci.glimpse.support.wrapped;
    exports com.metsci.glimpse.support.polygon;
    exports com.metsci.glimpse.event.mouse.swing;
    exports com.metsci.glimpse.plot.timeline.group;
    exports com.metsci.glimpse.support.swing;
    exports com.metsci.glimpse.plot.timeline.event;
    exports com.metsci.glimpse.plot.timeline.layout;
    exports com.metsci.glimpse.support;
    exports com.metsci.glimpse.painter.info;
    exports com.metsci.glimpse.support.shader;
    exports com.metsci.glimpse.painter;
    exports com.metsci.glimpse.layout.matcher;
    exports com.metsci.glimpse.axis.painter;
    exports com.metsci.glimpse.gl;
    exports com.metsci.glimpse.support.interval;
    exports com.metsci.glimpse.plot.timeline.event.paint;
    exports com.metsci.glimpse.axis;
    exports com.metsci.glimpse.axis.painter.label.time;
    exports com.metsci.glimpse.plot.timeline.data;
    exports com.metsci.glimpse.event.touch;
    exports com.metsci.glimpse.support.colormap;
    exports com.metsci.glimpse.support.atlas.painter;
    exports com.metsci.glimpse.painter.geo;
    exports com.metsci.glimpse.gl.shader;
    exports com.metsci.glimpse.axis.painter.label;
    exports com.metsci.glimpse.canvas;
    exports com.metsci.glimpse.support.settings;
    exports com.metsci.glimpse.plot.timeline;
    exports com.metsci.glimpse.plot.timeline.listener;
    exports com.metsci.glimpse.support.shader.line;
    exports com.metsci.glimpse.support.atlas.support;
    exports com.metsci.glimpse.event.key.newt;
    exports com.metsci.glimpse.layout;
    exports com.metsci.glimpse.painter.decoration;
    exports com.metsci.glimpse.gl.util;
    exports com.metsci.glimpse.plot.timeline.event.listener;
    exports com.metsci.glimpse.support.color;
    exports com.metsci.glimpse.support.popup;
    exports com.metsci.glimpse.plot.stacked;
    exports com.metsci.glimpse.event;
    exports com.metsci.glimpse.support.texture;
    exports com.metsci.glimpse.axis.listener.touch;
    exports com.metsci.glimpse.axis.listener.mouse;
    exports com.metsci.glimpse.support.atlas.shader;
    exports com.metsci.glimpse.axis.tagged.painter;
    exports com.metsci.glimpse.event.mouse.newt;
    exports com.metsci.glimpse.plot;
    exports com.metsci.glimpse.gl.texture;
    exports com.metsci.glimpse.painter.treemap;
    exports com.metsci.glimpse.plot.timeline.animate;
    exports com.metsci.glimpse.support.selection;
    exports com.metsci.glimpse;
    exports com.metsci.glimpse.axis.tagged;
    exports com.metsci.glimpse.support.projection;
    exports com.metsci.glimpse.axis.factory;
    exports com.metsci.glimpse.support.shader.triangle;
    exports com.metsci.glimpse.plot.timeline.painter;
    exports com.metsci.glimpse.support.shader.point;

    opens com.metsci.glimpse.core.colormap.matplotlib;
    opens com.metsci.glimpse.core.fonts.bitstream;
    opens com.metsci.glimpse.core.fonts.silkscreen;
    opens com.metsci.glimpse.core.icons.timeline;
    opens com.metsci.glimpse.core.shaders.atlas;
    opens com.metsci.glimpse.core.shaders.colormap;
    opens com.metsci.glimpse.core.shaders.HeatMapProgram;
    opens com.metsci.glimpse.core.shaders.line.DynamicLineSetPainter;
    opens com.metsci.glimpse.core.shaders.line.line_flat_color;
    opens com.metsci.glimpse.core.shaders.line.line_multi_color;
    opens com.metsci.glimpse.core.shaders.line.PolygonPainter;
    opens com.metsci.glimpse.core.shaders.point.PartialTaggedPointGradientProgram;
    opens com.metsci.glimpse.core.shaders.point.point_array_color;
    opens com.metsci.glimpse.core.shaders.point.point_array_color_size;
    opens com.metsci.glimpse.core.shaders.point.point_attribute_color_size;
    opens com.metsci.glimpse.core.shaders.point.point_flat_color;
    opens com.metsci.glimpse.core.shaders.triangle.array_color;
    opens com.metsci.glimpse.core.shaders.triangle.colortex1d;
    opens com.metsci.glimpse.core.shaders.triangle.colortex2d;
    opens com.metsci.glimpse.core.shaders.triangle.flat_color;
    opens com.metsci.glimpse.core.shaders.triangle.flat_color_stipple;
    opens com.metsci.glimpse.core.shaders.triangle.PolygonPainter;

    requires transitive com.metsci.glimpse.platformFixes;
    requires transitive com.metsci.glimpse.text;
    requires transitive com.metsci.glimpse.util;

    requires transitive miglayout.core;
    requires transitive com.google.common;
    requires transitive java.desktop;
    requires transitive java.logging;

    requires transitive jogamp.fat;
}