/*
 * Copyright (c) 2012, Metron, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Metron, Inc. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL METRON, INC. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.05 at 11:09:09 AM EST
//


package com.metsci.glimpse.dspl.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 *
 *         Textual information about a concept in the dataset. This extension of
 *         the base Info type adds a few additional fields that only apply to
 *         concepts.
 *
 *
 * <p>Java class for ConceptInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ConceptInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.google.com/dspl/2010}Info">
 *       &lt;sequence>
 *         &lt;element name="pluralName" type="{http://schemas.google.com/dspl/2010}Values" minOccurs="0"/>
 *         &lt;element name="totalName" type="{http://schemas.google.com/dspl/2010}Values" minOccurs="0"/>
 *         &lt;element name="singularNonCapitalizedName" type="{http://schemas.google.com/dspl/2010}Values" minOccurs="0"/>
 *         &lt;element name="pluralNonCapitalizedName" type="{http://schemas.google.com/dspl/2010}Values" minOccurs="0"/>
 *         &lt;element name="synonym" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://schemas.google.com/dspl/2010}ValuesGroup"/>
 *                 &lt;attribute name="confidence" default="high">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="high"/>
 *                       &lt;enumeration value="low"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConceptInfo", propOrder = {
    "pluralName",
    "totalName",
    "singularNonCapitalizedName",
    "pluralNonCapitalizedName",
    "synonym"
})
public class ConceptInfo
    extends Info
{

    protected Values pluralName;
    protected Values totalName;
    protected Values singularNonCapitalizedName;
    protected Values pluralNonCapitalizedName;
    protected List<ConceptInfo.Synonym> synonym;

    /**
     * Gets the value of the pluralName property.
     *
     * @return
     *     possible object is
     *     {@link Values }
     *
     */
    public Values getPluralName() {
        return pluralName;
    }

    /**
     * Sets the value of the pluralName property.
     *
     * @param value
     *     allowed object is
     *     {@link Values }
     *
     */
    public void setPluralName(Values value) {
        this.pluralName = value;
    }

    /**
     * Gets the value of the totalName property.
     *
     * @return
     *     possible object is
     *     {@link Values }
     *
     */
    public Values getTotalName() {
        return totalName;
    }

    /**
     * Sets the value of the totalName property.
     *
     * @param value
     *     allowed object is
     *     {@link Values }
     *
     */
    public void setTotalName(Values value) {
        this.totalName = value;
    }

    /**
     * Gets the value of the singularNonCapitalizedName property.
     *
     * @return
     *     possible object is
     *     {@link Values }
     *
     */
    public Values getSingularNonCapitalizedName() {
        return singularNonCapitalizedName;
    }

    /**
     * Sets the value of the singularNonCapitalizedName property.
     *
     * @param value
     *     allowed object is
     *     {@link Values }
     *
     */
    public void setSingularNonCapitalizedName(Values value) {
        this.singularNonCapitalizedName = value;
    }

    /**
     * Gets the value of the pluralNonCapitalizedName property.
     *
     * @return
     *     possible object is
     *     {@link Values }
     *
     */
    public Values getPluralNonCapitalizedName() {
        return pluralNonCapitalizedName;
    }

    /**
     * Sets the value of the pluralNonCapitalizedName property.
     *
     * @param value
     *     allowed object is
     *     {@link Values }
     *
     */
    public void setPluralNonCapitalizedName(Values value) {
        this.pluralNonCapitalizedName = value;
    }

    /**
     * Gets the value of the synonym property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the synonym property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSynonym().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConceptInfo.Synonym }
     *
     *
     */
    public List<ConceptInfo.Synonym> getSynonym() {
        if (synonym == null) {
            synonym = new ArrayList<ConceptInfo.Synonym>();
        }
        return this.synonym;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://schemas.google.com/dspl/2010}ValuesGroup"/>
     *       &lt;attribute name="confidence" default="high">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="high"/>
     *             &lt;enumeration value="low"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value",
        "conceptValue"
    })
    public static class Synonym {

        protected List<Value> value;
        protected com.metsci.glimpse.dspl.schema.Attribute.ConceptValue conceptValue;
        @XmlAttribute(name = "confidence")
        protected String confidence;

        /**
         * Gets the value of the value property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Value }
         *
         *
         */
        public List<Value> getValue() {
            if (value == null) {
                value = new ArrayList<Value>();
            }
            return this.value;
        }

        /**
         * Gets the value of the conceptValue property.
         *
         * @return
         *     possible object is
         *     {@link com.metsci.glimpse.dspl.schema.Attribute.ConceptValue }
         *
         */
        public com.metsci.glimpse.dspl.schema.Attribute.ConceptValue getConceptValue() {
            return conceptValue;
        }

        /**
         * Sets the value of the conceptValue property.
         *
         * @param value
         *     allowed object is
         *     {@link com.metsci.glimpse.dspl.schema.Attribute.ConceptValue }
         *
         */
        public void setConceptValue(com.metsci.glimpse.dspl.schema.Attribute.ConceptValue value) {
            this.conceptValue = value;
        }

        /**
         * Gets the value of the confidence property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getConfidence() {
            if (confidence == null) {
                return "high";
            } else {
                return confidence;
            }
        }

        /**
         * Sets the value of the confidence property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setConfidence(String value) {
            this.confidence = value;
        }

    }


    public String getPluralNameEnglish( )
    {
        Values values = getPluralName( );
        if ( values == null ) return null;

        return values.getValueEnglish( );
    }

    public String getTotalNameEnglish( )
    {
        Values values = getTotalName( );
        if ( values == null ) return null;

        return values.getValueEnglish( );
    }

    public String getSingularNonCapitalizedNameEnglish( )
    {
        Values values = getSingularNonCapitalizedName( );
        if ( values == null ) return null;

        return values.getValueEnglish( );
    }

    public String getPluralNonCapitalizedNameEnglish( )
    {
        Values values = getPluralNonCapitalizedName( );
        if ( values == null ) return null;

        return values.getValueEnglish( );
    }


}
